name: Build and Release

on:
  push:
    branches: ["main"]

# 添加权限配置
permissions:
  contents: write

env:
  PROJECT_NAME: cookie-sync

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v3
        with:
          version: "latest"
          
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Get version
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      # 添加创建 tag 的步骤
      - name: Create Tag
        run: |
          git tag "v${{ steps.get_version.outputs.version }}"
          git push origin "v${{ steps.get_version.outputs.version }}"
        
      - name: Build and zip
        run: |
          mkdir -p .output
          pnpm run build &&
          pnpm run build:firefox &&
          pnpm run zip &&
          pnpm run zip:firefox
          
      # 添加检查步骤
      - name: List files
        run: |
          echo "Content of .output directory:"
          ls -la .output/
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.get_version.outputs.version }}"
          name: "v${{ steps.get_version.outputs.version }}"
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            .output/*.zip
