name: Build and Release

on:
  push:
    branches: ["main"]

env:
  PROJECT_NAME: cookie-sync

jobs:
  Build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v3
        with:
          version: "latest"
          
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Get version
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        
      - name: Build and zip
        run: |
          pnpm run build &&
          pnpm run build:firefox &&
          pnpm run zip &&
          pnpm run zip:firefox
          
      - name: Create Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ steps.get_version.outputs.version }}"
          name: "v${{ steps.get_version.outputs.version }}"
          files: |
            .output/${{env.PROJECT_NAME}}-${{ steps.get_version.outputs.version }}-chrome.zip
            .output/${{env.PROJECT_NAME}}-${{ steps.get_version.outputs.version }}-firefox.zip
            .output/${{env.PROJECT_NAME}}-${{ steps.get_version.outputs.version }}-sources.zip
